### ISSUE TITLE
got some problem

### ISSUE THREAD

**Issue by hilaily** [AlexGaspar/docker-fbctf#4]
![image](https://cloud.githubusercontent.com/assets/5792904/15391088/e4b902d6-1df1-11e6-93bb-fc206db017bd.png)

I run it but when i visit it I got this in log, plz tell me where I did wrong

**Comment by AlexGaspar** [comment]
It looks like something is trying to connect using SSL over a non-SSL port.

What did you use to start the container?

**Comment by hilaily** [comment]
@AlexGaspar Today I installed docker-compose and then it is running all right. The problem got yesterday  is after I ran it with that three steps
